[build]
  command = "npm run generate"
  publish = "dist"

[[redirects]]
  from = "https://trd-web2.netlify.app/*"
  to = "https://tridia.ro/:splat"
  status = 301
  force = true
  
[[redirects]]
  from = "https://www.tridia.ro/*"
  to = "https://tridia.ro/:splat"
  status = 301
  force = true